### ISSUE TITLE
iPhone/iPad Movies Page - The Featured Image of the Movie to be played should be responsive

### ISSUE THREAD

**Issue by pratsajency** [ajency/short-film-window#240]
http://mobiletest.me/iphone_5_emulator/#u=http://www.shortfilmwindow.com/you-there/
http://mobiletest.me/ipad_mini_emulator/#u=http://www.shortfilmwindow.com/you-there/

![3t](https://cloud.githubusercontent.com/assets/3326712/7782463/f811a69a-0136-11e5-8368-e8fc4be66e99.png)

**Comment by renukaajency** [comment]
I didn't understand. its responsive.. It fills the screen. If it didn't fill then there would be a lot of empty spaces around the image.

**Comment by pratsajency** [comment]
@renukaajency 

The Image should have been resized and displayed accordingly for this screen, rather then cropping it and displaying a part of the image.

**Comment by renukaajency** [comment]
Actually the image has been resized, I can make either the height fir the screen or the width. Since this is a horizontal image, if the height didn't match the height of the screen there will be black/grey patches at the top and bottom of the screen. Is it alright? Like this:
![ss](https://cloud.githubusercontent.com/assets/11813307/7813791/7d4cb54c-03db-11e5-9c89-5298ee83aa69.jpg)
